### ISSUE TITLE
Providing the chechpoints.

### ISSUE THREAD

**Issue by YutingXiao** [QianyiWu/objsdf#1]
Thanks for the outstanding work!
I found that the training time is very long, It needs 120 hours for 10000 epochs training on 2080ti. 
Can you provide the checkpoints, It would help me a lot.

My best wish.

**Comment by QianyiWu** [comment]
Hi Yuting, 

Thanks for your interest in our work. The checkpoints of the toydesk dataset are provided in [here](https://drive.google.com/drive/folders/1IPEC8dCt-2e3UKe1V4gJ72QbPB4MlR5_?usp=sharing).

We set 10000 epochs in this training script just to inspect the performance change in the training. Usually, you will obtain a fairly good reconstruction result in the 2000 epochs.
