### ISSUE TITLE
About SDF bbox

### ISSUE THREAD

**Issue by MontaEllis** [QianyiWu/objsdf#10]
Hi Qianyi, I wonder why you use "SDF bbox" to clamp SDFs. Could you explain this? I haven't find any description in paper.

https://github.com/QianyiWu/objsdf/blob/cb4cbd1f98e0391ee2200f7018fc9efd1f5d16a5/code/model/network.py#L106

**Comment by QianyiWu** [comment]
Hi,
The reason behind it is just to make sure that all rays should at least intersect with one surface in the scene. With the clamping operation, the SDF will eventually become zero on the sphere surface which could be treated as a panorama background during rendering. 

This is a trick adopted from [VolSDF](https://github.com/lioryariv/volsdf/blob/a974c883eb70af666d8b4374e771d76930c806f3/code/model/network.py#L102). You can refer to the Sec B.3 in the supplementary of VolSDF for more details.

**Comment by MontaEllis** [comment]
Thanks a lot!
