### ISSUE TITLE
The mesh evaluation

### ISSUE THREAD

**Issue by kyleleey** [QianyiWu/objsdf#12]
Hi Qianyi,

I didn't find the corresponding script of mesh evaluation on Toydesk dataset in your codebase, and also in the objnerf codebase. I wonder how did you get the Chamfer Distance provided in the paper?

Because in the toydesk dataset, it seems that the gt point cloud is with many outliers, I wonder if there is any other operations that need to be done in addition to aligning the output mesh and gt with center and scale.

**Comment by QianyiWu** [comment]
Hi Kyleleey @kyleleey ,

Sorry for the late reply. I updated the mesh evaluation script for the Toydesk dataset in [here](https://github.com/QianyiWu/objsdf/blob/main/code/evaluation/compute_3d.py). The usage would be
`python compute_3d.py [path to gt mesh] [path to generated mesh] [center file]`
In this script, there will be a 3D box to crop the mesh into a valid [region.](https://github.com/QianyiWu/objsdf/blob/12f2b731ac138c99c26f12c98206301b70a21ae5/code/evaluation/compute_3d.py#L19) But I failed in finding the exact crop size for the desk 1 and 2... Sorry about that. It might be a little bit different than the current size (1.0) as shown in the script.

Hope this script would be helpful.

**Comment by kyleleey** [comment]
Hi Qianyi,

No problem, I totally understand this and thanks so much for providing this script
