### ISSUE TITLE
About Nerf++ processing

### ISSUE THREAD

**Issue by CeoiZidung** [QianyiWu/objsdf#3]
Hi~
Congrats on  your excellent job! I wanna ask whether you have added some procesing on nerf++. In your code, I saw the word, inverse_sphere_bg. But i didn't find the related network for background. 

Could u release this part of job?
Thanks!

**Comment by QianyiWu** [comment]
Hi~
Thanks for your interest. We didn't use the inverse_sphere_bg in ObjectSDF. But if you would like to test such a design proposed by NeRF++, you can refer to the codebase from [VolSDF](https://github.com/lioryariv/volsdf/blob/main/code/model/network_bg.py) to add this feature.

**Comment by CeoiZidung** [comment]
Thanks！ I already found it in volsdf!
