### ISSUE TITLE
Question about center.txt 

### ISSUE THREAD

**Issue by SuzyZhao0417** [QianyiWu/objsdf#5]
Hi, Thanks for your amazing work! I'm curious about the content in your center.txt.  From your code, the content is related to scale_mat and pose_matrix. As my own understanding it can help generate the sample sphere, could you please describe it clearly? Thank you for your reply, best wishes!

**Comment by QianyiWu** [comment]
Hi, the first three elements in 'center txt' is the coordinate of the center point in the original scene. The last element is the size of the whole scene. After the transformation, the entire scene will be located inside a sphere with a radius of 3.

This preprocessing is very similar to [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) and [here](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data). The main purpose is to make the whole scene in a suitable range.

**Comment by SuzyZhao0417** [comment]
> Hi, the first three elements in 'center txt' is the coordinate of the center point in the original scene. The last element is the size of the whole scene. After the transformation, the entire scene will be located inside a sphere with a radius of 3.
> 
> This preprocessing is very similar to [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) and [here](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data). The main purpose is to make the whole scene in a suitable range.

**Comment by SuzyZhao0417** [comment]
> Hi, the first three elements in 'center txt' is the coordinate of the center point in the original scene. The last element is the size of the whole scene. After the transformation, the entire scene will be located inside a sphere with a radius of 3.
> 
> This preprocessing is very similar to [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) and [here](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data). The main purpose is to make the whole scene in a suitable range.

Thanks for your reply! I understand the meaning

**Comment by rockywind** [comment]
> Hi, the first three elements in 'center txt' is the coordinate of the center point in the original scene. The last element is the size of the whole scene. After the transformation, the entire scene will be located inside a sphere with a radius of 3.
> 
> This preprocessing is very similar to [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) and [here](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data). The main purpose is to make the whole scene in a suitable range.

Hi,
how to modified the sphere's radius? I wanted to training the own dataset.
![0001](https://user-images.githubusercontent.com/14838781/224046011-fff9a8a4-d442-46f1-8d73-d3793cb70e62.jpg)

**Comment by QianyiWu** [comment]
> > Hi, the first three elements in 'center txt' is the coordinate of the center point in the original scene. The last element is the size of the whole scene. After the transformation, the entire scene will be located inside a sphere with a radius of 3.
> > This preprocessing is very similar to [here](https://github.com/zju3dv/manhattan_sdf/blob/main/docs/CUSTOM.md#camera-poses) and [here](https://github.com/Totoro97/NeuS/tree/main/preprocess_custom_data). The main purpose is to make the whole scene in a suitable range.
> 
> Hi, how to modified the sphere's radius? I wanted to training the own dataset. ![0001](https://user-images.githubusercontent.com/14838781/224046011-fff9a8a4-d442-46f1-8d73-d3793cb70e62.jpg)

You can modify the sphere's radius in the config file. But a better choice should be to scale the scene coordinate system to make it stay inside a sphere with a radius of 3. 

But currently, our method can not support getting object SDF from only a single image. It requires multiview images with camera pose and the corresponding instance mask for training.
