### ISSUE TITLE
Toydesk

### ISSUE THREAD

**Issue by Waterglaze** [QianyiWu/objsdf#8]
Hi Qianyi,

The link of Toydesk is out of date. May I have new sharing link? 
![image](https://user-images.githubusercontent.com/41203149/228121893-23a16ba4-cdd3-4a22-968b-553bd387bdc3.png)

**Comment by QianyiWu** [comment]
Hi,

I uploaded a backup version of the Toydesk data [here](https://drive.google.com/file/d/1mhZblow5WGXsdua3zWf_PaJjGE686_Ss/view?usp=sharing). Note that the copyright of this data belongs to the original author. 

Thanks.

**Comment by Waterglaze** [comment]
> 

Thank you for your help!
