### ISSUE TITLE
Training cost, Eval file and Quality of mesh

### ISSUE THREAD

**Issue by Waterglaze** [QianyiWu/objsdf#9]
Hi Qian Wu,

Thank you for your help in dataset and Sorry for that I still have problems in evaluation process.

- I have trained a model with toydesk2, it takes 15 hours in training process (2000 epoch with 3080Ti), and I wonder how long it takes you to train the model for toydesk? 
- I find the ply files in the exp folder (default output folder), but their quality is not that good. I want to know how I can obtain the mesh on the quality that you displayed. Following is the color mesh I generate based on a training output in final epoch.
![image](https://user-images.githubusercontent.com/41203149/229041465-edd16d71-924a-4fae-b788-447e193d3f6c.png)
- when I execute the eval file, I find there are many attributions that the ToydeskDataset don't have such as get_scale_mat() function and scan_id. Moreover, I wonder what scan_id means? I defined it as -1, and it doesn't report any error but give me a 'killed' print.

Thank you for your taking time to going through my questions and wait for your reply.
Best Regards

**Comment by QianyiWu** [comment]
Hi Waterglaze,
1. The training speed you mentioned is reasonable. I also tried toydesk2 in 3090 and it will take ~15 hours to train 2000 epochs.
2. The default marching cube resolution is 100 [here](https://github.com/QianyiWu/objsdf/blob/b7e754b297c4c7f45d8dc3034e09b97f43b6acef/code/confs/toydesk2.conf#L14). You can increase it to a higher number for better mesh visualization, such as 256.
3. Sorry about the misunderstanding of the evaluation script. The 'eval.py' is not for this project... I forget to remove it... If you would like to evaluate the model, I provide the mIOU and PSNR evaluation script [here](https://github.com/QianyiWu/objsdf/blob/main/code/evaluation/compute_segm_metric.py).

**Comment by Waterglaze** [comment]
Hi Qianyi Wu,

Thank you for your answer! It really helps!

I changed the resolution to 256, it looks better, and then to 512, it out of memory, haha. In addition, as you said that the resolution is marching cube resolution, is it only for marching cube? Does that mean that I can use the model trained with marching cube resolution 100 to infer a high-resolution (e.g., 512) mesh? But I didn't find the code file that can directly extract a mesh from the model, shall I get them from training code?

**Comment by QianyiWu** [comment]
Hi Waterglaze,

As the output of ObjectSDF is the signed distance function of each object, you can use the trained model with different marching cube resolutions to recover a mesh from it. 

In this project, I didn't create an individual script to extract mesh. But it is easy to refer [here](https://github.com/QianyiWu/objsdf/blob/cb4cbd1f98e0391ee2200f7018fc9efd1f5d16a5/code/training/objsdf_train.py#L191-L199) to create such a script.

**Comment by Waterglaze** [comment]
Thank you for your help!
